In [1]:
# 主要测试 torch 的语法
import torch

# python语法


索引的开闭: 
* random.randint(a, b) 返回的是[a, b],
* 其他的注入torch[a: b] 是[a, b), range(start, end, step)


In [ ]:
(1, 2) + (3, 4)  # (1, 2, 3, 4)


(1, 2, 3, 4)

In [3]:
def complex_function(a, b=2, *args, c=3, **kwargs):
    print(f"position variables, \ta: {a}")
    print(f"default variables, \tb: {b}")
    print(f"variable position variables, \targs: {args}")
    print(f"keyword variables, \tc: {c}")
    print(f"variable kwargs, \tkargs: {kwargs}")

# 调用函数
complex_function(1, 4, 5, 6, c=7, d=8, e=9)
# 输出:
# a: 1, b: 4
# args: (5, 6)
# c: 7
# kwargs: {'d': 8, 'e': 9}

position variables, 	a: 1
default variables, 	b: 4
variable position variables, 	args: (5, 6)
keyword variables, 	c: 7
variable kwargs, 	kargs: {'d': 8, 'e': 9}


## zip

In [4]:
#
list1 = [1, 2, 3]
list2 = ['a', 'b', 'c']
# 多个可迭代对象
list3 = [True, False, True]
zipped = zip(list1, list2, list3)
print(list(zipped))

# 当传入的可迭代对象长度不一致时，zip 只会配对到最短的一个可迭代对象的长度，剩余的元素会被丢弃。
list1 = [1, 2, 3]
list2 = ['a', 'b']
zipped = zip(list1, list2)
print(list(zipped))

# unzip
zipped = [(1, 'a'), (2, 'b'), (3, 'c')]
# 解压
unzipped = zip(*zipped)
list1, list2 = map(list, unzipped)  # 使用 map 将解压结果转化为列表
print(list1)  # [1, 2, 3]
print(list2)  # ['a', 'b', 'c']

[(1, 'a', True), (2, 'b', False), (3, 'c', True)]
[(1, 'a'), (2, 'b')]
[1, 2, 3]
['a', 'b', 'c']


# torch 语法总结

In [5]:
import torch
from d2l import torch as d2l

print("MPS available:", torch.backends.mps.is_available())
print("MPS built:", torch.backends.mps.is_built())

print(d2l.try_gpu())

MPS available: True
MPS built: True
cpu


In [6]:
import torch
# 创建一个形状为 (1, 2, 3, 4) 的张量
x = torch.rand(1, 2, 3, 4)
print(x.shape)  # 输出: torch.Size([1, 2, 3, 4])
x.reshape(2, 3, -1).shape

torch.Size([1, 2, 3, 4])


torch.Size([2, 3, 4])

In [7]:
import torch

# 创建一个三维数组
Y = np.arange(24).reshape(2, 3, 4)
print("原始数组 Y 的形状:", Y.shape)
print("原始数组 Y:")
print(Y)

# 重塑数组
reshaped_Y = Y.reshape((-1, Y.shape[-1]))
print("\n重塑后数组 reshaped_Y 的形状:", reshaped_Y.shape)
print("重塑后数组 reshaped_Y:")
print(reshaped_Y)

NameError: name 'np' is not defined

## torch.stack

In [ ]:
# torch.stack: https://pytorch.org/docs/stable/generated/torch.stack.html

# 使用 torch.stack 沿着第1维堆叠

tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])
stacked_1 = torch.stack([tensor1, tensor2, tensor3], dim=1)

# 使用 torch.stack 沿着第0维堆叠
stacked_0 = torch.stack([tensor1, tensor2, tensor3], dim=0)
print("Stacked Tensor along dim=0:")
print(stacked_0)

print("Stacked Tensor along dim=1:")
print(stacked_1)

# 创建多个 2D 张量
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])
tensor3 = torch.tensor([[9, 10], [11, 12]])
# 使用 torch.stack 沿着第2维堆叠
stacked_2 = torch.stack([tensor1, tensor2, tensor3], dim=2)
print("Stacked Tensor along dim=2:")
print(stacked_2)

Stacked Tensor along dim=0:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Stacked Tensor along dim=1:
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])
Stacked Tensor along dim=2:
tensor([[[ 1,  5,  9],
         [ 2,  6, 10]],

        [[ 3,  7, 11],
         [ 4,  8, 12]]])


In [ ]:
# zip torch
X = torch.tensor([[[0.0, 1.0, 2.0],
                   [3.0, 4.0, 5.0],
                   [6.0, 7.0, 8.0]],

                  [[1.0, 2.0, 3.0],
                   [4.0, 5.0, 6.0],
                   [7.0, 8.0, 9.0]]])

K = torch.tensor([[[0.0, 1.0],
                   [2.0, 3.0]],

                  [[1.0, 2.0],
                   [3.0, 4.0]]])

print("X.shape", X.shape, "K.shape", K.shape)
for x, k in zip(X, K):
    print("x, k => ", x, k)

X.shape torch.Size([2, 3, 3]) K.shape torch.Size([2, 2, 2])
x, k =>  tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]) tensor([[0., 1.],
        [2., 3.]])
x, k =>  tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) tensor([[1., 2.],
        [3., 4.]])


## reshape输入辨析

In [ ]:
import torch

# 输入是reshape是到底是元组合适分开的参数

# == 输入是元组的函数
torchVar = torch.normal(mean=0.0, std=0.01, size=(12, 3))
# Returns a tensor filled with random numbers from a normal distribution with mean 0 and variance 1
_ = torch.randn(size=(12, 3)).shape
torchVar.reshape((-1, 2))            # 重设形状为(?, 2)

_ = torch.zeros((100 - 4, 4)).shape    # torch.Size([96, 4])

_ = torch.arange(6, 10).shape        # torch.Size([4])
_ = torch.arange(24)                 # torch.Size[24]



# d2l 相关的函数
# d2l.load_array((features[:n_train], labels[:n_train])
# _ = torch.tensor([0, 2])



# == 输入是分开的参数
print(torchVar.shape)
_.size()


torch.Size([12, 3])


torch.Size([24])

## torch.cat

In [ ]:
import torch

# 创建 b1 和 b2
b1 = torch.arange(6).reshape(3, 1, 2)
b2 = torch.arange(7, 13).reshape(3, 1, 2)

# 打印 b1 和 b2
print("b1: \n", b1, "\nb2: \n", b2)
# unsqueeze(0)：将 b1 和 b2 在第 0 维上扩展成形状为 (1, 3, 1, 2)，这样 torch.cat 才能在第 0 维上拼接。
print("unsqueeze(0): ", b1.unsqueeze(0))

# 使用 torch.cat 拼接沿第 0 维, 输入一个(2, 3, 1, 2)的矩阵
result = torch.cat((b1.unsqueeze(0), b2.unsqueeze(0)), dim=0)
print("Shape of result: \n", result.shape)

# 总结：dim中没有带数字1，即保留下channels维度其他的求和 => (1, 3, 1, 1)
# (0 + 1 + 7 + 8) / 4 = 4;        (2 + 3 + 9 + 10) / 4 = 16
print(result.mean(dim=(0, 2, 3), keepdim=True, dtype=torch.float32))

b1: 
 tensor([[[0, 1]],

        [[2, 3]],

        [[4, 5]]]) 
b2: 
 tensor([[[ 7,  8]],

        [[ 9, 10]],

        [[11, 12]]])
unsqueeze(0):  tensor([[[[0, 1]],

         [[2, 3]],

         [[4, 5]]]])
Shape of result: 
 torch.Size([2, 3, 1, 2])
tensor([[[[4.]],

         [[6.]],

         [[8.]]]])


## torch.mean

## torch.unsqueeze
https://docs.pytorch.org/docs/stable/generated/torch.unsqueeze.html#torch-unsqueeze

torch.unsqueeze(input, dim) 就在在dim处加入一个空维度。 其中dim范围[-(input.dim+1), dim]； 即当dim为负数时，dim = dim + input.dim() + 1。例如imput.dim()=2, -3 = 0, -2 = 1, -1 = 2; 是一一对应的。

In [ ]:
import torch
x = torch.tensor([1, 2, 3, 4])

print(x.unsqueeze(0))
# tensor([[1, 2, 3, 4]])

torch.unsqueeze(x, 0)
# tensor([[1, 2, 3, 4]])

torch.unsqueeze(x, 0).unsqueeze(0)
# tensor([[[1, 2, 3, 4]]])

tensor([[1, 2, 3, 4]])


tensor([[[1, 2, 3, 4]]])

## torch.repeat

torch.repeat() 按指定次数沿每个维度复制（tile）张量的数据。

torch.repeat_interleave(input, repeats, dim=None) 是 逐元素重复（element-wise repeat），而 repeat 是 逐维度重复（tile repeat）。
- input: 输入张量。
- repeats: 每个元素重复的次数，可以是：
- 一个整数（所有元素重复相同次数）；
- 一个与 input.shape[dim] 相同的 1D 张量（每个元素重复不同次数）。
- dim: 沿哪个维度重复（默认是扁平化后再重复）。

In [ ]:
import torch

x = torch.tensor([1, 2, 3])  # shape: (3,)
out = x.repeat(2)  # 重复整个 x 两次
print(out)  # tensor([1, 2, 3, 1, 2, 3])

x = torch.tensor([[1, 2], [3, 4]])  # shape: (2, 2)
out = x.repeat(2, 3)  # 沿第0维重复2次，沿第1维重复3次
print(out)

x = torch.tensor([1, 2, 3])  # shape: (3,)
out = x.repeat(2, 3)  # 因为原始张量 x 是一维的 (3,)，而 .repeat() 需要两个维度的信息 (2, 3)，所以 PyTorch 会自动在最前面添加一个维度，使其变为 (1, 3)。这一步称为“自动左补 1”。
print(out)

x = torch.tensor([1, 2, 3])  # shape: (3,)
out = x.repeat((2, 1)) # .repeat() 可以接受元组参数指定每个维度的重复次数
#                          当参数维度 > 原始维度时，会自动在左侧补充维度（本例中补充了第0维）原始张量(3,), 自动调整为(1, 3)
#                          最终输出是二维张量，包含两行相同的 [1, 2, 3]
#                          这种用法常用于需要将一维数据扩展为二维矩阵的场景（如批处理操作）
print("(2,1)", out)




# ===== torch.repeat_interleave
x = torch.tensor([1, 2, 3])
out = torch.repeat_interleave(x, 2)
print(out)
# 输出: tensor([1, 1, 2, 2, 3, 3])

x = torch.tensor([[1, 2], [3, 4]]) # shape: (2, 2)
out = torch.repeat_interleave(x, 2, dim=0)
print(out)
# 输出:
# tensor([[1, 2],
#         [1, 2],
#         [3, 4],
#         [3, 4]])

x = torch.tensor([10, 20, 30])
repeats = torch.tensor([1, 2, 3])
out = torch.repeat_interleave(x, repeats)
print(out)
# 输出: tensor([10, 20, 20, 30, 30, 30])

x = torch.tensor([[1, 2], [3, 4]])
# shape: (2, 2)
out = torch.repeat_interleave(x, repeats=2, dim=1)
print(out)
# 输出:
# tensor([[1, 1, 2, 2],
#         [3, 3, 4, 4]])

tensor([1, 2, 3, 1, 2, 3])
tensor([[1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4],
        [1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4]])
tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3]])
(2,1) tensor([[1, 2, 3],
        [1, 2, 3]])
tensor([1, 1, 2, 2, 3, 3])
tensor([[1, 2],
        [1, 2],
        [3, 4],
        [3, 4]])
tensor([10, 20, 20, 30, 30, 30])
tensor([[1, 1, 2, 2],
        [3, 3, 4, 4]])


## torch mask
tensor[mask] , tensor 沿着 mask（掩码）取值，也叫 布尔索引（boolean indexing）,  结果是一个一维向量, tensor[number]
mask 就是一个 布尔（bool）类型的 tensor，每个位置是 True 或 False，它和原始 tensor 形状一致或可广播，用来表示：

布尔索引 tensor[mask] 时，mask.shape 必须能和 tensor.shape 完全对齐，否则就会报错。

In [ ]:
import torch

# 1. 过滤掉值为False的元素
a = torch.tensor([10, 20, 30, 40])
mask = torch.tensor([True, False, True, False])

result = a[mask]
print(result)  # tensor([10, 30])

# 2. 过滤掉对角线
eye = torch.eye(3)
print(eye)
# tensor([[1., 0., 0.],
#         [0., 1., 0.],
#         [0., 0., 1.]])

mask = (1 - eye).bool()
print(mask)
# tensor([[False,  True,  True],
#         [ True, False,  True],
#         [ True,  True, False]])

a = torch.tensor([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])

result = a[mask]
print(result)  # tensor([20, 30, 40, 60, 70, 80])

tensor([10, 30])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[False,  True,  True],
        [ True, False,  True],
        [ True,  True, False]])
tensor([20, 30, 40, 60, 70, 80])


In [10]:
x = torch.tensor([1,2,3])
x.shape

torch.Size([3])

# 常见表示和符号总结

行向量：
* 在Pytorch官网文档符号上，[Liner](https://docs.pytorch.org/docs/stable/generated/torch.nn.Linear.html#torch.nn.Linear) $x$ 、[RNN](https://docs.pytorch.org/docs/stable/generated/torch.nn.RNN.html#torch.nn.RNN) 的 $x_t$
* 在Pytorch python输出上，torch.random(3)一般也是行向量。
* 在《动手深度学习》里面，$x^i$ 一般理解为行向量

