In [7]:
# 主要测试 torch 的语法
import torch

# python语法

In [8]:
(1, 2) + (3, 4)  # (1, 2, 3, 4)

(1, 2, 3, 4)

In [9]:
def complex_function(a, b=2, *args, c=3, **kwargs):
    print(f"position variables, \ta: {a}")
    print(f"default variables, \tb: {b}")
    print(f"variable position variables, \targs: {args}")
    print(f"keyword variables, \tc: {c}")
    print(f"variable kwargs, \tkargs: {kwargs}")

# 调用函数
complex_function(1, 4, 5, 6, c=7, d=8, e=9)
# 输出:
# a: 1, b: 4
# args: (5, 6)
# c: 7
# kwargs: {'d': 8, 'e': 9}

position variables, 	a: 1
default variables, 	b: 4
variable position variables, 	args: (5, 6)
keyword variables, 	c: 7
variable kwargs, 	kargs: {'d': 8, 'e': 9}


## zip

In [10]:
#
list1 = [1, 2, 3]
list2 = ['a', 'b', 'c']
# 多个可迭代对象
list3 = [True, False, True]
zipped = zip(list1, list2, list3)
print(list(zipped))

# 当传入的可迭代对象长度不一致时，zip 只会配对到最短的一个可迭代对象的长度，剩余的元素会被丢弃。
list1 = [1, 2, 3]
list2 = ['a', 'b']
zipped = zip(list1, list2)
print(list(zipped))

# unzip
zipped = [(1, 'a'), (2, 'b'), (3, 'c')]
# 解压
unzipped = zip(*zipped)
list1, list2 = map(list, unzipped)  # 使用 map 将解压结果转化为列表
print(list1)  # [1, 2, 3]
print(list2)  # ['a', 'b', 'c']

[(1, 'a', True), (2, 'b', False), (3, 'c', True)]
[(1, 'a'), (2, 'b')]
[1, 2, 3]
['a', 'b', 'c']


# torch 语法总结

In [11]:
import torch
# 创建一个形状为 (1, 2, 3, 4) 的张量
x = torch.rand(1, 2, 3, 4)
print(x.shape)  # 输出: torch.Size([1, 2, 3, 4])
x.reshape(2, 3, -1).shape

torch.Size([1, 2, 3, 4])


torch.Size([2, 3, 4])

## torch.stack

In [12]:
# torch.stack: https://pytorch.org/docs/stable/generated/torch.stack.html

# 使用 torch.stack 沿着第1维堆叠

tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])
stacked_1 = torch.stack([tensor1, tensor2, tensor3], dim=1)

# 使用 torch.stack 沿着第0维堆叠
stacked_0 = torch.stack([tensor1, tensor2, tensor3], dim=0)
print("Stacked Tensor along dim=0:")
print(stacked_0)

print("Stacked Tensor along dim=1:")
print(stacked_1)

# 创建多个 2D 张量
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])
tensor3 = torch.tensor([[9, 10], [11, 12]])
# 使用 torch.stack 沿着第2维堆叠
stacked_2 = torch.stack([tensor1, tensor2, tensor3], dim=2)
print("Stacked Tensor along dim=2:")
print(stacked_2)

Stacked Tensor along dim=0:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Stacked Tensor along dim=1:
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])
Stacked Tensor along dim=2:
tensor([[[ 1,  5,  9],
         [ 2,  6, 10]],

        [[ 3,  7, 11],
         [ 4,  8, 12]]])


In [13]:
# zip torch
X = torch.tensor([[[0.0, 1.0, 2.0],
                   [3.0, 4.0, 5.0],
                   [6.0, 7.0, 8.0]],

                  [[1.0, 2.0, 3.0],
                   [4.0, 5.0, 6.0],
                   [7.0, 8.0, 9.0]]])

K = torch.tensor([[[0.0, 1.0],
                   [2.0, 3.0]],

                  [[1.0, 2.0],
                   [3.0, 4.0]]])

print("X.shape", X.shape, "K.shape", K.shape)
for x, k in zip(X, K):
    print("x, k => ", x, k)

X.shape torch.Size([2, 3, 3]) K.shape torch.Size([2, 2, 2])
x, k =>  tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]) tensor([[0., 1.],
        [2., 3.]])
x, k =>  tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) tensor([[1., 2.],
        [3., 4.]])


## reshape输入辨析

In [14]:
# 输入是reshape是到底是元组合适分开的参数

# == 输入是元组的函数
torchVar = torch.normal(mean=0.0, std=0.01, size=(12, 3))
torchVar.reshape((-1, 2))
_ = torch.zeros((100 - 4, 4)).shape    # torch.Size([96, 4])
_ = torch.arange(6, 10).shape        # torch.Size([4])
_ = torch.randn(size=(12, 3)).shape


# d2l 相关的函数
# d2l.load_array((features[:n_train], labels[:n_train])
# _ = torch.tensor([0, 2])



# == 输入是分开的参数
_


torch.Size([12, 3])

## torch.cat

In [ ]:
import torch

# 创建 b1 和 b2
b1 = torch.arange(6).reshape(3, 1, 2)
b2 = torch.arange(7, 13).reshape(3, 1, 2)

# 打印 b1 和 b2
print("b1: \n", b1, "\nb2: \n", b2)
# unsqueeze(0)：将 b1 和 b2 在第 0 维上扩展成形状为 (1, 3, 1, 2)，这样 torch.cat 才能在第 0 维上拼接。
print("unsqueeze(0): ", b1.unsqueeze(0))

# 使用 torch.cat 拼接沿第 0 维, 输入一个(2, 3, 1, 2)的矩阵
result = torch.cat((b1.unsqueeze(0), b2.unsqueeze(0)), dim=0)
print("Shape of result: \n", result.shape)

# 总结：dim中没有带数字1，即保留下channels维度其他的求和 => (1, 3, 1, 1)
# (0 + 1 + 7 + 8) / 4 = 4;        (2 + 3 + 9 + 10) / 4 = 16
print(result.mean(dim=(0, 2, 3), keepdim=True, dtype=torch.float32))

b1: 
 tensor([[[0, 1]],

        [[2, 3]],

        [[4, 5]]]) 
b2: 
 tensor([[[ 7,  8]],

        [[ 9, 10]],

        [[11, 12]]])
unsqueeze(0):  tensor([[[[0, 1]],

         [[2, 3]],

         [[4, 5]]]])
Shape of result: 
 torch.Size([2, 3, 1, 2])
tensor([[[[4.]],

         [[6.]],

         [[8.]]]])


## torch.mean